{
 "title": "Networkpolicy dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Packets allowed by NetworkPolicy going from pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(policy_accept_counter{type=\"fw\"}[1m])",
     "legendFormat": "Policy: {{policy}}, pod: {{exported_pod}}"
    }
   ]
  },
  {
   "title": "Packets allowed by NetworkPolicy going to pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(policy_accept_counter{type=\"tw\"}[1m])",
     "legendFormat": "Policy: {{policy}}, pod: {{exported_pod}}"
    }
   ]
  },
  {
   "title": "Dropped packets going from pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(no_policy_drop_counter{type=\"fw\"}[1m])",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Dropped packets going to pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(no_policy_drop_counter{type=\"tw\"}[1m])",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  }
 ]
}