opensearch:
  s3:
    accessKey:
    secretKey:
    secret:

  accounts:
    - username:
      password:
      cookie:
      secret:

  certificates:
    ca:
      commonName: example.com
      duration: 21600h
      renewBefore: 360h
      keySize: 2048
      usages: []
      organization:
    admin:
      enabled: true
      commonName: example.com
      duration: 21600h
      renewBefore: 360h
      keySize: 2048
      usages:
      - server auth
      - client auth
      organization:
      secret:
    transport:
      enabled: true
      commonName: example.com
      duration: 21600h
      renewBefore: 360h
      keySize: 2048
      usages:
      - server auth
      - client auth
      organization:
      secret:
