{{- range $account := .Values.opensearch.accounts }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $account.secret }}
type: Opaque
data:
    username: {{ $account.username | b64enc }}
    password: {{ $account.password | b64enc }}
    {{ if $account.cookie -}}
    cookie: {{ $account.cookie | b64enc }}
    {{- end}}
{{- end }}
