global:
  issuer: letsencrypt-prod
  verifyTls: true

user:
  namespaces:
    - set-me
    - production
    - staging

prometheus:
  storage:
    size: 15Gi
  retention:
    size: 12GiB
    age:  3d

opa:
  imageRegistry:
    enforcement: deny

  networkPolicies:
    enforcement: deny

  resourceRequests:
    enforcement: deny
